months=set(["january","february","march","april","may","june"])
print("the original set")
print (months)
print("adding other momths to the set")
months.add("july")
months.add("agust")
months.add("september")
months.add("0ctober")
months.add("november")
months.add("december")
print("printing modified set")
print(months)
   
